name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'How to bump version'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - prepatch
          - prerelease

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.node-version'

      - name: Bump version
        id: bump_version
        run: |
          echo "newversion=$(npm version --no-git-tag-version ${{ github.event.inputs.bump_type }})" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b feature/bump-version-${{ steps.bump_version.outputs.newversion }}
          git add .
          git commit -m "Bump version to ${{ steps.bump_version.outputs.newversion }}"
          git push origin feature/bump-version-${{ steps.bump_version.outputs.newversion }}

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Bump version to ${{ steps.bump_version.outputs.newversion }}" \
            --body "This PR bumps the version to ${{ steps.bump_version.outputs.newversion }}." \
            --head "feature/bump-version-${{ steps.bump_version.outputs.newversion }}" \
            --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
